[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "MercyNJ", email = "mercinjuguna@gmail.com" }
]
requires-python = ">=3.11.7"
dependencies = [
    "alembic>=1.20.0",
    "fastapi>=0.141.1",
    "psycopg>=3.3.6",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[tool.uv]
package = false
